name: Lib Components CICD

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  CICD:
    uses: mairie360/CICD/.github/workflows/front-libs-cicd.yml@v3.1.1
    with:
      cicd_version: v3.1.1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      N8N_WEBHOOK_SECRET: ${{ secrets.N8N_WEBHOOK_SECRET }}
