name: Main CI Entry Point

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: Run tests once
    runs-on: ubuntu-latest
    outputs:
      tests_passed: ${{ steps.tests.outcome == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Unit tests
        id: tests
        run: npm test

  build_and_lighthouse:
    name: Build Storybook & Run Lighthouse
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.result == 'success'
    outputs:
      src_changed: ${{ steps.check_src.outputs.changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Check if src/ has changed
        id: check_src
        run: |
          git fetch origin main
          CHANGED=$(git diff --name-only origin/main...HEAD | grep '^src/' || true)
          echo "changed=$([[ -n \"$CHANGED\" ]] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        if: steps.check_src.outputs.changed == 'true'
        run: npm ci

      - name: Build Storybook
        if: steps.check_src.outputs.changed == 'true'
        run: npm run build-storybook

      - name: Serve Storybook
        if: steps.check_src.outputs.changed == 'true'
        run: npm run local-storybook &

      - name: Generate Lighthouse URLs
        if: steps.check_src.outputs.changed == 'true'
        run: npm run lhci:urls

      - name: Run Lighthouse
        if: steps.check_src.outputs.changed == 'true'
        run: npm run lhci:run

      - name: Check accessibility
        if: steps.check_src.outputs.changed == 'true'
        run: npm run lhci:check

      - name: Upload Storybook artifact
        if: steps.check_src.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static
